### ISSUE TITLE
Cannot assign to property: '$selection' is immutable

### ISSUE THREAD

**Issue by OxyFlax** [QuynhNguyen/SlidingTabView#1]
Currently with beta 4 we have the following issue: 
`SlidingTabView.swift:93:14: Cannot assign to property: '$selection' is immutable`
when binding the two selection inside init `self.$selection = selection`

**Comment by OxyFlax** [comment]
#2 Fixed in this PR

**Comment by QuynhNguyen** [comment]
Merged
