### ISSUE TITLE
The project is running but not archiving

### ISSUE THREAD

**Issue by m-kul** [QuynhNguyen/SlidingTabView#11]
I have implemented slidingTabView succesfully and it is working fine. Only problem is when I try to archive the project, it looks like it cannot find SwiftUI library and it give errors like: Cannot find View in scope. How can I fix this problem?

**Comment by WojciechBrzezinski** [comment]
I have identical problem, did you manage to solve that?

**Comment by m-kul** [comment]
I don't remember exactly but I think it had something to do with the @available. I have made it a local library and changed the version to my min version.
